"""PDF checklist generator — creates printable PDF checklists for government services."""

from __future__ import annotations

import io
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)


def _strip_non_ascii(text: str) -> str:
    """Remove characters that Helvetica (built-in FPDF font) cannot render.

    Keeps ASCII + common Latin characters. Replaces everything else
    (Urdu, Arabic, CJK, etc.) with a placeholder or strips it.
    """
    if not text:
        return text
    # Replace non-renderable chars with '?' to preserve readability
    return text.encode("ascii", errors="replace").decode("ascii")


def _safe_text(text: str, max_len: int = 0) -> str:
    """Make text safe for Helvetica PDF rendering."""
    text = _strip_non_ascii(text)
    if max_len and len(text) > max_len:
        text = text[:max_len] + "..."
    return text


def generate_checklist_pdf(data: dict[str, Any]) -> bytes:
    """Generate a printable PDF checklist for a government service.

    Args:
        data: QueryResponse-like dict with answer, requirements, steps, fee, etc.

    Returns:
        PDF bytes.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("fpdf2 not installed — install with: pip install fpdf2")
        return _generate_text_fallback(data)

    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(1, 65, 28)  # PakGreen
        pdf.cell(0, 12, "PakGuide - Service Checklist", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(4)

        # Separator
        pdf.set_draw_color(1, 65, 28)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        # Answer summary
        if data.get("answer"):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            safe_answer = _safe_text(data["answer"], 500)
            pdf.multi_cell(0, 5, safe_answer, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)

        # Eligibility
        if data.get("eligibility"):
            _section(pdf, "Eligibility")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, _safe_text(data["eligibility"]), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)

        # Required Documents
        requirements = data.get("requirements") or []
        if requirements:
            _section(pdf, "Required Documents")
            for i, req in enumerate(requirements, 1):
                _checkbox_item(pdf, f"{i}. {_safe_text(req)}")

        # Steps
        steps = data.get("steps") or []
        if steps:
            _section(pdf, "Steps / Procedure")
            for i, step in enumerate(steps, 1):
                _numbered_item(pdf, i, _safe_text(step))

        # Details grid
        details = []
        if data.get("fee"):
            details.append(("Fee", _safe_text(data["fee"], 100)))
        if data.get("processing_time"):
            details.append(("Processing Time", _safe_text(data["processing_time"], 100)))
        if data.get("application_method"):
            details.append(("Application Method", _safe_text(data["application_method"], 100)))
        if data.get("application_url"):
            details.append(("Apply Online", _safe_text(data["application_url"], 100)))

        if details:
            _section(pdf, "Key Details")
            for label, value in details:
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(50, 6, f"{label}:", new_x="RIGHT", new_y="LAST")
                pdf.set_font("Helvetica", "", 10)
                pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

        # Contact info
        contact = data.get("contact_info") or {}
        if isinstance(contact, dict) and any(contact.values()):
            _section(pdf, "Contact Information")
            pdf.set_font("Helvetica", "", 10)
            if contact.get("phone"):
                pdf.cell(0, 6, f"Phone: {_safe_text(str(contact['phone']))}", new_x="LMARGIN", new_y="NEXT")
            if contact.get("address"):
                pdf.cell(0, 6, f"Address: {_safe_text(str(contact['address']))}", new_x="LMARGIN", new_y="NEXT")
            if contact.get("website"):
                pdf.cell(0, 6, f"Website: {_safe_text(str(contact['website']))}", new_x="LMARGIN", new_y="NEXT")

        # Footer
        pdf.ln(8)
        pdf.set_draw_color(1, 65, 28)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, "Generated by PakGuide (pakmind.ai) - Always verify with official sources before acting.", align="C")

         return pdf.output()


    except Exception as exc:
        logger.error("PDF generation error: %s — falling back to text", exc)
        return _generate_text_fallback(data)


def _section(pdf, title: str) -> None:
    """Add a section header."""
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(1, 65, 28)
    pdf.cell(0, 8, _safe_text(title), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)


def _checkbox_item(pdf, text: str) -> None:
    """Add a checkbox item (printable checklist style)."""
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    y = pdf.get_y()
    # Draw checkbox
    pdf.rect(12, y + 1, 4, 4)
    pdf.set_x(20)
    pdf.multi_cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")


def _numbered_item(pdf, num: int, text: str) -> None:
    """Add a numbered step."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(1, 65, 28)
    pdf.cell(8, 6, f"{num}.", new_x="RIGHT", new_y="LAST")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")


def _generate_text_fallback(data: dict[str, Any]) -> bytes:
    """Fallback: generate a plain-text checklist if fpdf2 is unavailable or fails."""
    lines = ["PAKGUIDE SERVICE CHECKLIST", "=" * 40, ""]

    if data.get("answer"):
        lines.append(_safe_text(data["answer"], 300))
        lines.append("")

    if data.get("requirements"):
        lines.append("REQUIRED DOCUMENTS:")
        for i, req in enumerate(data["requirements"], 1):
            lines.append(f"  [ ] {i}. {_safe_text(req)}")
        lines.append("")

    if data.get("steps"):
        lines.append("STEPS:")
        for i, step in enumerate(data["steps"], 1):
            lines.append(f"  {i}. {_safe_text(step)}")
        lines.append("")

    for key in ("fee", "processing_time", "application_method", "application_url"):
        if data.get(key):
            lines.append(f"{key.replace('_', ' ').title()}: {_safe_text(str(data[key]), 100)}")

    lines.append("")
    lines.append("Generated by PakGuide - Verify with official sources.")
    return "\n".join(lines).encode("utf-8")
